spring.application.name=product-service


#server
server.port=8082

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#JWT
jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

internal.security.key=${INTERNAL_SECURITY_KEY}


# Removes the 'path' field from default error responses
server.error.include-path=never
# Removes the 'exception' class name
server.error.include-exception=false
# Removes the stack trace
server.error.include-stacktrace=never
